spring:
  application:
    name: admin-server
  #Connect to Zipkin Server, its optional, if it runs on same server and port   
  zipkin:    base-url: http://localhost:9411/zipkin/

server:
  port: 9000

#Disable Eureka client temporarily 
eureka:  client:    enabled: false

#spring:
#  mail:
#    host: localhost
#  boot:
#    admin:
#      notify:
#        mail:
#          to: venkatrami.ambati@gmail.com
#          enabled: true
#          from: venkatrami.ambati@gmail.com
